-- locations
Tracker:AddLocations("locations/treasure_radar.jsonc")
Tracker:AddLocations("locations/mechaniloids.jsonc")
Tracker:AddLocations("locations/shops.jsonc")
Tracker:AddLocations("locations/lagrano_ruins.jsonc")
Tracker:AddLocations("locations/central_tower.jsonc")
Tracker:AddLocations("locations/tianna_camp.jsonc")
Tracker:AddLocations("locations/gaudile_laboratory.jsonc")
Tracker:AddLocations("locations/eternal_forest.jsonc")
Tracker:AddLocations("locations/ulfat_factory.jsonc")
Tracker:AddLocations("locations/gimialla_mine.jsonc")
Tracker:AddLocations("locations/vanallia_desert.jsonc")
Tracker:AddLocations("locations/vanallia_desert_base.jsonc")
Tracker:AddLocations("locations/melda_ore_plant.jsonc")
Tracker:AddLocations("locations/grave_ruins_base.jsonc")
Tracker:AddLocations("locations/far_east_hq.jsonc")